### ISSUE TITLE
Sauce: failures on IE

### ISSUE THREAD

**Issue by aub** [department-of-veterans-affairs/vets-website#6149]
I get the following errors when running the e2e tests on IE

```
TEST FAILURE: 6 errors during execution,  11 assertions failed, 352 passed. (80m 8s)

✖ burials/00-all-fields.e2e.spec

  - Begin application (3m 27s)
  Timed out while waiting for element <input[name="root_deathDateYear"]> to be present for 60000 milliseconds.  - expected "visible" but got: "not found"
      at /Users/aubrey/code/vets-website/test/burials/00-all-fields.e2e.spec.js:42:12
      at Object.BeginApplication [as Begin application] (/Users/aubrey/code/vets-website/test/e2e/e2e-helpers.js:70:7)

✖ edu-benefits/1990e/01-all-fields.e2e.spec

  - Begin application (3m 11s)
  Expected element <.js-test-location> to have attribute "data-location" not contain: "/applicant/information" in 60000ms  - expected "not contain '/applicant/information'" but got: "/1990e/applicant/information"
      at Object.expectNavigateAwayFrom (/Users/aubrey/code/vets-website/test/e2e/e2e-helpers.js:77:17)
      at /Users/aubrey/code/vets-website/test/edu-benefits/1990e/01-all-fields.e2e.spec.js:30:16
      at Object.BeginApplication [as Begin application] (/Users/aubrey/code/vets-website/test/e2e/e2e-helpers.js:70:7)

✖ edu-benefits/1990n/01-all-fields.e2e.spec

  - Begin application (3m 11s)
  Expected element <.js-test-location> to have attribute "data-location" not contain: "/applicant/information" in 60000ms  - expected "not contain '/applicant/information'" but got: "/1990n/applicant/information"
      at Object.expectNavigateAwayFrom (/Users/aubrey/code/vets-website/test/e2e/e2e-helpers.js:77:17)
      at /Users/aubrey/code/vets-website/test/edu-benefits/1990n/01-all-fields.e2e.spec.js:28:16
      at Object.BeginApplication [as Begin application] (/Users/aubrey/code/vets-website/test/e2e/e2e-helpers.js:70:7)

✖ edu-benefits/1995/01-all-fields.e2e.spec

  - Begin application (3m 47s)
  Expected element <.js-test-location> to have attribute "data-location" not contain: "/military/service" in 60000ms  - expected "not contain '/military/service'" but got: "/1995/military/service"
      at Object.expectNavigateAwayFrom (/Users/aubrey/code/vets-website/test/e2e/e2e-helpers.js:77:17)
      at /Users/aubrey/code/vets-website/test/edu-benefits/1995/01-all-fields.e2e.spec.js:48:16
      at Object.BeginApplication [as Begin application] (/Users/aubrey/code/vets-website/test/e2e/e2e-helpers.js:70:7)

✖ edu-benefits/5490/01-all-fields.e2e.spec

  - Begin application (3m 10s)
  Expected element <.js-test-location> to have attribute "data-location" not contain: "/applicant/information" in 60000ms  - expected "not contain '/applicant/information'" but got: "/5490/applicant/information"
      at Object.expectNavigateAwayFrom (/Users/aubrey/code/vets-website/test/e2e/e2e-helpers.js:77:17)
      at /Users/aubrey/code/vets-website/test/edu-benefits/5490/01-all-fields.e2e.spec.js:33:16
      at Object.BeginApplication [as Begin application] (/Users/aubrey/code/vets-website/test/e2e/e2e-helpers.js:70:7)

✖ edu-benefits/5495/01-all-fields.e2e.spec

  - Begin application (3m 21s)
  Expected element <.js-test-location> to have attribute "data-location" not contain: "/applicant/information" in 60000ms  - expected "not contain '/applicant/information'" but got: "/5495/applicant/information"
      at Object.expectNavigateAwayFrom (/Users/aubrey/code/vets-website/test/e2e/e2e-helpers.js:77:17)
      at /Users/aubrey/code/vets-website/test/edu-benefits/5495/01-all-fields.e2e.spec.js:30:16
      at Object.BeginApplication [as Begin application] (/Users/aubrey/code/vets-website/test/e2e/e2e-helpers.js:70:7)

✖ hca/00-all-fields.e2e.spec

  - Begin application (3m 30s)
  Expected element <.js-test-location> to have attribute "data-location" not contain: "/veteran-information/birth-information" in 60000ms  - expected "not contain '/veteran-information/birth-information'" but got: "/veteran-information/birth-information"
      at Object.expectNavigateAwayFrom (/Users/aubrey/code/vets-website/test/e2e/e2e-helpers.js:77:17)
      at /Users/aubrey/code/vets-website/test/hca/00-all-fields.e2e.spec.js:34:16
      at Object.BeginApplication [as Begin application] (/Users/aubrey/code/vets-website/test/e2e/e2e-helpers.js:70:7)

✖ messaging/00-required.e2e.spec

  - Begin application (4m 22s)
  Timed out while waiting for element <#messaging-app> to be present for 150000 milliseconds.  - expected "visible" but got: "not found"
      at /Users/aubrey/code/vets-website/test/messaging/00-required.e2e.spec.js:22:8
      at Object.BeginApplication [as Begin application] (/Users/aubrey/code/vets-website/test/e2e/e2e-helpers.js:70:7)

✖ messaging/01-required-desktop.e2e.spec

  - Begin application (3m 6s)
  Timed out while waiting for element <.usa-alert-success> to be present for 60000 milliseconds.  - expected "visible" but got: "not found"
      at /Users/aubrey/code/vets-website/test/messaging/01-required-desktop.e2e.spec.js:57:8
      at Object.BeginApplication [as Begin application] (/Users/aubrey/code/vets-website/test/e2e/e2e-helpers.js:70:7)

✖ pensions/00-all-fields.e2e.spec

  - Begin application (3m 17s)
  Timed out while waiting for element <input[name="root_servicePeriods_0_serviceBranch"]> to be present for 60000 milliseconds.  - expected "visible" but got: "not found"
      at /Users/aubrey/code/vets-website/test/pensions/00-all-fields.e2e.spec.js:31:12
      at Object.BeginApplication [as Begin application] (/Users/aubrey/code/vets-website/test/e2e/e2e-helpers.js:70:7)

✖ rx/00-required.e2e.spec

  - Begin application (2m 26s)
  Timed out while waiting for element <#rx-active> to be present for 60000 milliseconds.  - expected "visible" but got: "not found"
      at /Users/aubrey/code/vets-website/test/rx/00-required.e2e.spec.js:20:8
      at Object.BeginApplication [as Begin application] (/Users/aubrey/code/vets-website/test/e2e/e2e-helpers.js:70:7)
```

**Comment by aub** [comment]
Moving to vets.gov-team
