### ISSUE TITLE
Sauce: failures on Firefox

### ISSUE THREAD

**Issue by aub** [department-of-veterans-affairs/vets-website#6150]
We have some failing tests against Firefox when running on Sauce. At least some of them are caused by an issue where the test harness seems to select the wrong value from a select box.

```
TEST FAILURE: 20 errors during execution,  3 assertions failed, 602 passed. (85m 37s)

✖ edu-benefits/1990/01-all-fields.e2e.spec

  - Begin application (6m 30s)

✖ edu-benefits/1995/01-all-fields.e2e.spec

  - Begin application (4m 2s)

✖ login/login.e2e.spec

  - Begin application (45.354s)
  Testing if the URL contains "http://fake_logout_url".  - expected "http://fake_logout_url" but got: "http://www.dnsrsearch.com/index.php?origURL=http%3A//fake_logout_url/&r=http%3A//localhost%3A3333/&bc="
      at Object.windowHandlesCallback (/Users/aubrey/code/vets-website/test/login/login.e2e.spec.js:32:21)

✖ messaging/00-required.e2e.spec

  - Begin application (2m 21s)
  Failed [fail]: ('[n/a]: [moderate] id attribute value must be unique\nSee https://dequeuniversity.com/rules/axe/2.3/duplicate-id?application=axe undefined undefined)
  See https://dequeuniversity.com/rules/axe/2.3/duplicate-id?application=axeAPI

  <input class="msg-hidden-radio" name="messagingMoveToFolder" id="msg-move-to-Test Folder 1" value="123" type="radio">
  #messaging-content > div > div:nth-child(2) > table > tbody > tr:nth-child(1) > td:nth-child(5) > .msg-move-to > form > fieldset > ul > li:nth-child(1) > div > input[type="radio"]
  <input class="msg-hidden-radio" name="messagingMoveToFolder" id="msg-move-to-Test Folder 2" value="456" type="radio">
  #messaging-content > div > div:nth-child(2) > table > tbody > tr:nth-child(1) > td:nth-child(5) > .msg-move-to > form > fieldset > ul > li:nth-child(2) > div > input[type="radio"]"
      at /Users/aubrey/code/vets-website/test/util/nightwatch-commands/axeCheck.js:56:19
      at Array.forEach (native)
      at Object.<anonymous> (/Users/aubrey/code/vets-website/test/util/nightwatch-commands/axeCheck.js:48:16)

✖ post-911-gib-status/01-authed.e2e.spec

  - Begin application (52.416s)
  Expected element <#enrollment-0 h4> text to contain: "11/01/2012 to 12/01/2012 at Purdue University"  - expected "contain '11/01/2012 to 12/01/2012 at Purdue University'" but got: "10/31/2012 to 11/30/2012 at Purdue University (11902614)"
      at /Users/aubrey/code/vets-website/test/post-911-gib-status/01-authed.e2e.spec.js:23:19
      at Object.BeginApplication [as Begin application] (/Users/aubrey/code/vets-website/test/e2e/e2e-helpers.js:70:7)
```

**Comment by aub** [comment]
Moving to vets.gov-team
