### ISSUE TITLE
Sauce: failures on android

### ISSUE THREAD

**Issue by aub** [department-of-veterans-affairs/vets-website#6153]
I get the following failures when running tests against android on Sauce:

```
TEST FAILURE: 12 errors during execution,  10 assertions failed, 542 passed. (135m 14s)

✖ edu-benefits/1990/01-all-fields.e2e.spec

  - Begin application (11m 19s)

✖ edu-benefits/5490/01-all-fields.e2e.spec

  - Begin application (10m 52s)
  Expected element <.js-test-location> to have attribute "data-location" not contain: "/personal-information/direct-deposit" in 60000ms - element was not found  - expected "present" but got: "not present"
      at Object.expectNavigateAwayFrom (/Users/aubrey/code/vets-website/test/e2e/e2e-helpers.js:77:17)
      at /Users/aubrey/code/vets-website/test/edu-benefits/5490/01-all-fields.e2e.spec.js:166:16
      at Object.BeginApplication [as Begin application] (/Users/aubrey/code/vets-website/test/e2e/e2e-helpers.js:70:7)

✖ hca/00-all-fields.e2e.spec

  - Begin application (10m 30s)
  Failed [fail]: ('No scan results found' undefined undefined)
      at Object.<anonymous> (/Users/aubrey/code/vets-website/test/util/nightwatch-commands/axeCheck.js:40:19)
  Expected element <.js-test-location> to have attribute "data-location" not contain: "/insurance-information/va-facility" in 60000ms - element was not found  - expected "present" but got: "not present"
      at Object.expectNavigateAwayFrom (/Users/aubrey/code/vets-website/test/e2e/e2e-helpers.js:77:17)
      at /Users/aubrey/code/vets-website/test/hca/00-all-fields.e2e.spec.js:139:16
      at Object.BeginApplication [as Begin application] (/Users/aubrey/code/vets-website/test/e2e/e2e-helpers.js:70:7)

✖ messaging/00-required.e2e.spec

  - Begin application (4m 37s)
  Failed [fail]: ('[n/a]: [critical] Buttons must have discernible text\nSee https://dequeuniversity.com/rules/axe/2.3/button-name?application=axe undefined undefined)
  See https://dequeuniversity.com/rules/axe/2.3/button-name?application=axeAPI

  <button class="usa-button-unstyled messaging-folder-nav-close" type="button"><i class="fa fa-close"></i></button>
  #messaging-nav > button.usa-button-unstyled.messaging-folder-nav-close"
      at /Users/aubrey/code/vets-website/test/util/nightwatch-commands/axeCheck.js:56:19
      at Array.forEach (native)
      at Object.<anonymous> (/Users/aubrey/code/vets-website/test/util/nightwatch-commands/axeCheck.js:48:16)
  Failed [fail]: ('[n/a]: [moderate] id attribute value must be unique\nSee https://dequeuniversity.com/rules/axe/2.3/duplicate-id?application=axe undefined undefined)
  See https://dequeuniversity.com/rules/axe/2.3/duplicate-id?application=axeAPI

  <input type="radio" class="msg-hidden-radio" name="messagingMoveToFolder" id="msg-move-to-Test Folder 1" value="123">
  #messaging-content > div > div:nth-child(2) > table > tbody > tr:nth-child(1) > td:nth-child(5) > .msg-move-to > form > fieldset > ul > li:nth-child(1) > div > input[type="radio"]
  <input type="radio" class="msg-hidden-radio" name="messagingMoveToFolder" id="msg-move-to-Test Folder 2" value="456">
  #messaging-content > div > div:nth-child(2) > table > tbody > tr:nth-child(1) > td:nth-child(5) > .msg-move-to > form > fieldset > ul > li:nth-child(2) > div > input[type="radio"]"
      at /Users/aubrey/code/vets-website/test/util/nightwatch-commands/axeCheck.js:56:19
      at Array.forEach (native)
      at Object.<anonymous> (/Users/aubrey/code/vets-website/test/util/nightwatch-commands/axeCheck.js:48:16)
  Timed out while waiting for element <textarea[name="messageText"]> to be visible for 150000 milliseconds.  - expected "visible" but got: "not visible"
      at /Users/aubrey/code/vets-website/test/messaging/00-required.e2e.spec.js:37:8
      at Object.BeginApplication [as Begin application] (/Users/aubrey/code/vets-website/test/e2e/e2e-helpers.js:70:7)

✖ messaging/01-required-desktop.e2e.spec

  - Begin application (2m 57s)
  Timed out while waiting for element <textarea[name="messageText"]> to be visible for 60000 milliseconds.  - expected "visible" but got: "not visible"
      at /Users/aubrey/code/vets-website/test/messaging/01-required-desktop.e2e.spec.js:47:8
      at Object.BeginApplication [as Begin application] (/Users/aubrey/code/vets-website/test/e2e/e2e-helpers.js:70:7)

✖ pensions/00-all-fields.e2e.spec

  - Begin application (13m 4s)
  Failed [fail]: ('No scan results found' undefined undefined)
      at Object.<anonymous> (/Users/aubrey/code/vets-website/test/util/nightwatch-commands/axeCheck.js:40:19)
  Expected element <.js-test-location> to have attribute "data-location" not contain: "/household/spouse-marriages/0" in 60000ms - element was not found  - expected "present" but got: "not present"
      at Object.expectNavigateAwayFrom (/Users/aubrey/code/vets-website/test/e2e/e2e-helpers.js:77:17)
      at /Users/aubrey/code/vets-website/test/pensions/00-all-fields.e2e.spec.js:113:16
      at Object.BeginApplication [as Begin application] (/Users/aubrey/code/vets-website/test/e2e/e2e-helpers.js:70:7)

✖ rx/00-required.e2e.spec

  - Begin application (2m 12s)
  Expected element <.rx-prescription-card> to be visible - element was not found  - expected "visible" but got: "not found"
      at /Users/aubrey/code/vets-website/test/rx/00-required.e2e.spec.js:30:15
      at Object.BeginApplication [as Begin application] (/Users/aubrey/code/vets-website/test/e2e/e2e-helpers.js:70:7)
```

**Comment by aub** [comment]
Moving to vets.gov-team
