### ISSUE TITLE
Sauce: failures on ios

### ISSUE THREAD

**Issue by aub** [department-of-veterans-affairs/vets-website#6154]
Here are some failures I get when running Sauce against ios. Most of these appear to be timeout issues, so we may be able to fix a bunch of them by simply raising the timeouts. I did notice that the ios emulator on sauce seems to be dreadfully slow.

```
TEST FAILURE:  24 assertions failed, 147 passed. (166m 26s)

✖ burials/00-all-fields.e2e.spec

  - Begin application (4m 20s)
  Timed out while waiting for element <body> to be present for 60000 milliseconds.  - expected "visible" but got: "not found"
      at /Users/aubrey/code/vets-website/test/burials/00-all-fields.e2e.spec.js:13:8
      at Object.BeginApplication [as Begin application] (/Users/aubrey/code/vets-website/test/e2e/e2e-helpers.js:70:7)

✖ disability-benefits/e2e/02.claim-files.e2e.spec

  - Begin application (3m 39s)
  Timed out while waiting for element <body> to be present for 60000 milliseconds.  - expected "visible" but got: "not found"
      at Object.logIn (/Users/aubrey/code/vets-website/test/e2e/login-helpers.js:81:6)
      at /Users/aubrey/code/vets-website/test/disability-benefits/e2e/02.claim-files.e2e.spec.js:13:18
      at Object.BeginApplication [as Begin application] (/Users/aubrey/code/vets-website/test/e2e/e2e-helpers.js:70:7)

✖ disability-benefits/e2e/04.claim-ask-va.e2e.spec

  - Begin application (5m 20s)
  Timed out while waiting for element <body> to be present for 60000 milliseconds.  - expected "visible" but got: "not found"
      at Object.logIn (/Users/aubrey/code/vets-website/test/e2e/login-helpers.js:81:6)
      at /Users/aubrey/code/vets-website/test/disability-benefits/e2e/04.claim-ask-va.e2e.spec.js:16:18
      at Object.BeginApplication [as Begin application] (/Users/aubrey/code/vets-website/test/e2e/e2e-helpers.js:70:7)

✖ disability-benefits/e2e/05.claim-document-request.e2e.spec

  - Begin application (3m 49s)
  Timed out while waiting for element <body> to be present for 60000 milliseconds.  - expected "visible" but got: "not found"
      at Object.logIn (/Users/aubrey/code/vets-website/test/e2e/login-helpers.js:81:6)
      at /Users/aubrey/code/vets-website/test/disability-benefits/e2e/05.claim-document-request.e2e.spec.js:14:18
      at Object.BeginApplication [as Begin application] (/Users/aubrey/code/vets-website/test/e2e/e2e-helpers.js:70:7)

✖ edu-benefits/1990/01-all-fields.e2e.spec

  - Begin application (4m 57s)
  Timed out while waiting for element <body> to be present for 60000 milliseconds.  - expected "visible" but got: "not found"
      at /Users/aubrey/code/vets-website/test/edu-benefits/1990/01-all-fields.e2e.spec.js:12:8
      at Object.BeginApplication [as Begin application] (/Users/aubrey/code/vets-website/test/e2e/e2e-helpers.js:70:7)

✖ edu-benefits/1990e/01-all-fields.e2e.spec

  - Begin application (4m 56s)
  Timed out while waiting for element <body> to be present for 60000 milliseconds.  - expected "visible" but got: "not found"
      at /Users/aubrey/code/vets-website/test/edu-benefits/1990e/01-all-fields.e2e.spec.js:14:8
      at Object.BeginApplication [as Begin application] (/Users/aubrey/code/vets-website/test/e2e/e2e-helpers.js:70:7)

✖ edu-benefits/1990n/01-all-fields.e2e.spec

  - Begin application (4m 23s)
  Timed out while waiting for element <body> to be present for 60000 milliseconds.  - expected "visible" but got: "not found"
      at /Users/aubrey/code/vets-website/test/edu-benefits/1990n/01-all-fields.e2e.spec.js:13:8
      at Object.BeginApplication [as Begin application] (/Users/aubrey/code/vets-website/test/e2e/e2e-helpers.js:70:7)

✖ edu-benefits/1995/01-all-fields.e2e.spec

  - Begin application (4m 45s)
  Timed out while waiting for element <body> to be present for 60000 milliseconds.  - expected "visible" but got: "not found"
      at /Users/aubrey/code/vets-website/test/edu-benefits/1995/01-all-fields.e2e.spec.js:14:8
      at Object.BeginApplication [as Begin application] (/Users/aubrey/code/vets-website/test/e2e/e2e-helpers.js:70:7)

✖ edu-benefits/5490/01-all-fields.e2e.spec

  - Begin application (4m 36s)
  Timed out while waiting for element <body> to be present for 60000 milliseconds.  - expected "visible" but got: "not found"
      at /Users/aubrey/code/vets-website/test/edu-benefits/5490/01-all-fields.e2e.spec.js:14:8
      at Object.BeginApplication [as Begin application] (/Users/aubrey/code/vets-website/test/e2e/e2e-helpers.js:70:7)

✖ edu-benefits/5495/01-all-fields.e2e.spec

  - Begin application (4m 45s)
  Timed out while waiting for element <body> to be present for 60000 milliseconds.  - expected "visible" but got: "not found"
      at /Users/aubrey/code/vets-website/test/edu-benefits/5495/01-all-fields.e2e.spec.js:14:8
      at Object.BeginApplication [as Begin application] (/Users/aubrey/code/vets-website/test/e2e/e2e-helpers.js:70:7)

✖ facility-locator/00-required.e2e.spec

  - Begin application (3m 38s)
  Timed out while waiting for element <body> to be present for 60000 milliseconds.  - expected "visible" but got: "not found"
      at /Users/aubrey/code/vets-website/test/facility-locator/00-required.e2e.spec.js:14:8
      at Object.BeginApplication [as Begin application] (/Users/aubrey/code/vets-website/test/e2e/e2e-helpers.js:70:7)

✖ gibct/00-required.e2e.spec

  - Begin application (3m 50s)
  Timed out while waiting for element <body> to be present for 60000 milliseconds.  - expected "visible" but got: "not found"
      at /Users/aubrey/code/vets-website/test/gibct/00-required.e2e.spec.js:16:8
      at Object.BeginApplication [as Begin application] (/Users/aubrey/code/vets-website/test/e2e/e2e-helpers.js:70:7)

✖ hca/00-all-fields.e2e.spec

  - Begin application (5m 54s)
  Timed out while waiting for element <body> to be present for 60000 milliseconds.  - expected "visible" but got: "not found"
      at /Users/aubrey/code/vets-website/test/hca/00-all-fields.e2e.spec.js:13:8
      at Object.BeginApplication [as Begin application] (/Users/aubrey/code/vets-website/test/e2e/e2e-helpers.js:70:7)

✖ hca/01-sip.e2e.spec

  - Begin application (3m 37s)
  Timed out while waiting for element <body> to be present for 60000 milliseconds.  - expected "visible" but got: "not found"
      at Object.initSaveInProgressMock (/Users/aubrey/code/vets-website/test/e2e/hca-helpers.js:302:6)
      at /Users/aubrey/code/vets-website/test/hca/01-sip.e2e.spec.js:9:18
      at Object.BeginApplication [as Begin application] (/Users/aubrey/code/vets-website/test/e2e/e2e-helpers.js:70:7)

✖ login/login.e2e.spec

  - Begin application (4m 41s)
  Failed [equal]: (There should be 2 windows open)  - expected "2" but got: "1"
      at Object.windowHandlesCallback (/Users/aubrey/code/vets-website/test/login/login.e2e.spec.js:29:21)
  Testing if the URL contains "http://fake_logout_url".  - expected "http://fake_logout_url" but got: "http://localhost:3333/#"
      at Object.windowHandlesCallback (/Users/aubrey/code/vets-website/test/login/login.e2e.spec.js:32:21)

✖ messaging/00-required.e2e.spec

  - Begin application (5m 21s)
  Timed out while waiting for element <body> to be present for 60000 milliseconds.  - expected "visible" but got: "not found"
      at Object.testUnauthedUserFlow (/Users/aubrey/code/vets-website/test/e2e/login-helpers.js:102:6)
      at /Users/aubrey/code/vets-website/test/messaging/00-required.e2e.spec.js:15:18
      at Object.BeginApplication [as Begin application] (/Users/aubrey/code/vets-website/test/e2e/e2e-helpers.js:70:7)

✖ messaging/01-required-desktop.e2e.spec

  - Begin application (4m 57s)
  Timed out while waiting for element <body> to be present for 60000 milliseconds.  - expected "visible" but got: "not found"
      at Object.logIn (/Users/aubrey/code/vets-website/test/e2e/login-helpers.js:81:6)
      at /Users/aubrey/code/vets-website/test/messaging/01-required-desktop.e2e.spec.js:13:18
      at Object.BeginApplication [as Begin application] (/Users/aubrey/code/vets-website/test/e2e/e2e-helpers.js:70:7)

✖ pensions/00-all-fields.e2e.spec

  - Begin application (5m 20s)
  Timed out while waiting for element <body> to be present for 60000 milliseconds.  - expected "visible" but got: "not found"
      at /Users/aubrey/code/vets-website/test/pensions/00-all-fields.e2e.spec.js:13:8
      at Object.BeginApplication [as Begin application] (/Users/aubrey/code/vets-website/test/e2e/e2e-helpers.js:70:7)

✖ post-911-gib-status/00-unauthed.e2e.spec

  - Begin application (3m 41s)
  Timed out while waiting for element <body> to be present for 60000 milliseconds.  - expected "visible" but got: "not found"
      at Object.testUnauthedUserFlow (/Users/aubrey/code/vets-website/test/e2e/login-helpers.js:102:6)
      at /Users/aubrey/code/vets-website/test/post-911-gib-status/00-unauthed.e2e.spec.js:12:18
      at Object.BeginApplication [as Begin application] (/Users/aubrey/code/vets-website/test/e2e/e2e-helpers.js:70:7)

✖ post-911-gib-status/01-authed.e2e.spec

  - Begin application (4m 34s)
  Timed out while waiting for element <body> to be present for 60000 milliseconds.  - expected "visible" but got: "not found"
      at Object.logIn (/Users/aubrey/code/vets-website/test/e2e/login-helpers.js:81:6)
      at /Users/aubrey/code/vets-website/test/post-911-gib-status/01-authed.e2e.spec.js:13:18
      at Object.BeginApplication [as Begin application] (/Users/aubrey/code/vets-website/test/e2e/e2e-helpers.js:70:7)

✖ rx/00-required.e2e.spec

  - Begin application (4m 56s)
  Timed out while waiting for element <body> to be present for 60000 milliseconds.  - expected "visible" but got: "not found"
      at Object.testUnauthedUserFlow (/Users/aubrey/code/vets-website/test/e2e/login-helpers.js:102:6)
      at /Users/aubrey/code/vets-website/test/rx/00-required.e2e.spec.js:15:18
      at Object.BeginApplication [as Begin application] (/Users/aubrey/code/vets-website/test/e2e/e2e-helpers.js:70:7)

✖ sanity-check/smoke-test.e2e.spec

  - Begin application (5m 12s)
  Timed out while waiting for element <body> to be present for 60000 milliseconds.  - expected "visible" but got: "not found"
      at /Users/aubrey/code/vets-website/test/sanity-check/smoke-test.e2e.spec.js:12:8
      at Object.BeginApplication [as Begin application] (/Users/aubrey/code/vets-website/test/e2e/e2e-helpers.js:70:7)

✖ user-profile/e2e/user-profile.e2e.spec

  - Begin application (4m 53s)
  Timed out while waiting for element <body> to be present for 60000 milliseconds.  - expected "visible" but got: "not found"
      at Object.logIn (/Users/aubrey/code/vets-website/test/e2e/login-helpers.js:81:6)
      at /Users/aubrey/code/vets-website/test/user-profile/e2e/user-profile.e2e.spec.js:9:18
      at Object.BeginApplication [as Begin application] (/Users/aubrey/code/vets-website/test/e2e/e2e-helpers.js:70:7)
```

**Comment by aub** [comment]
Moving to vets.gov-team
